SHELL := /bin/bash

URL          := "{{{ url }}}"
MAIN         := main.go
TESTCASE_DIR := ../testcases

go.mod:
	go mod init

$(TESTCASE_DIR):
	mkdir -p ../testcases
	oj d ${URL} -d ${TESTCASE_DIR}

.PHONY: init
init: go.mod $(TESTCASE_DIR)

.PHONY: test
test: init
	oj t -c "go run ${MAIN}" -d ${TESTCASE_DIR} -j 10

.PHONY: submit
submit: test
	oj s ${URL} ${MAIN} -y
